StockBarang/Controllers/ItemController.cs
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using StockBarang.Helper;
using StockBarang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockBarang.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult List(int page = 1)
        {
            var user = Helper.MySqlHelper.GetUserByName(User.Identity.Name);
            var model = new ItemListModel
            {
                Items = Helper.MySqlHelper.Getstock_items(user.Id, page)
            };
            Helper.PagingHelper.FillPaging(model, page, Helper.MySqlHelper.GetTotalstock_items(user.Id));
            return View(model);
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            var model = new ItemCreateModel
            {
                StoreList = Helper.MySqlHelper.GetStores(MySqlHelper.GetUserByName(User.Identity.Name).Id),
                MaterialList = Helper.MySqlHelper.GetMaterials()
            };
            return View(model);
        }

        // POST: Store/Create
        [HttpPost]
        public ActionResult Create(ItemCreateModel model)
        {
            try
            {
                MySqlHelper.InsertItem(new Item() { IdItem = model.ID, ItemUrl = model.ItemUrl, StoreUrl = model.Store });
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                var modl = new ItemCreateModel
                {
                    StoreList = Helper.MySqlHelper.GetStores(MySqlHelper.GetUserByName(User.Identity.Name).Id),
                    MaterialList = Helper.MySqlHelper.GetMaterials()
                };
                return View(modl);
            }
        }

        // GET: Store/Create
        public ActionResult Stock(string id)
        {
            var model = new ItemStockModel
            {
                Item = Helper.MySqlHelper.GetItem(id)
            };
            return View(model);
        }

        // POST: Store/Create
        [HttpPost]
        public ActionResult Stock(ItemStockModel model)
        {
            try
            {
                var store = MySqlHelper.GetCompleteStore(model.Item.StoreUrl);
                switch (store.Marketplace)
                {
                    case "Tokopedia":
                        TokopediaHelper.ChangeStock(model.Item.ItemUrl, store, model.stock);
                        break;
                    case "Bukalapak":
                        BukalapakHelper.ChangeStock(model.Item.ItemUrl, store, model.stock);
                        break;
                }
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                var modl = new ItemStockModel
                {
                    Item = Helper.MySqlHelper.GetItem(model.Item.IdItem)
                };
                return View(modl);
            }
        }
    }
}

StockBarang/Views/Item/Create.cshtml
@model StockBarang.Models.ItemCreateModel
@{
    ViewBag.Title = "Add new Item";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "Item", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Store, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Store, new SelectList(Model.StoreList, "store_url", "storename"))
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ID, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ID, new SelectList(Model.MaterialList, "id", "nama"))
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ItemUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ItemUrl, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockBarang/Views/Item/List.cshtml
@model StockBarang.Models.ItemListModel
@{
    ViewBag.Title = "Store List";
}

<h2>@ViewBag.Title.</h2><br />
<button onclick="javascript:location='/item/create'">Add Store</button><br />
<div class="list-group">
    @for (var i = 1; i <= Model.Items.Count; i++)
    {
        var c = Model.Items.ElementAt(i-1);
        @:<div class="list-group-item list-group-item-action flex-column align-items-start">
            @:<div class="d-flex w-100 justify-content-between">
                  @:<a href="/item/delete?id=@c.iditem"><small>Delete</small></a>
                  @:<a href="/item/stock?id=@c.iditem"><small>Change Stock</small></a>
            @:</div>
            @:<p class="mb-1">
            @:<h4 class="mb-1">@c.itemname</h4>
            @:Store : @c.store_url<br />
            @:</p>
        @:</div>
    }
</div>
<nav aria-label="...">
    <ul class="pagination">
        @for (var i = 1; i <= Model.Paging.Count; i++)
        {
            StockBarang.Helper.PagingEntity paging = Model.Paging[i - 1];
            @:<li class="page-item @(paging.disabled?"disabled":"")@(paging.active?"active":"")"><a class="page-link" href="@paging.href" tabindex="-1">@paging.PagingText</a></li>
        }
    </ul>
</nav>

StockBarang/Views/Item/Stock.cshtml
@model StockBarang.Models.ItemStockModel
@{
    ViewBag.Title = "Change item stock";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Stock", "Item", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <h4>Change stock for @Model.Item.itemname.</h4>
    <hr />
    @Html.HiddenFor(m => m.Item.item_url, new { @class = "form-control" })
    @Html.HiddenFor(m => m.Item.store_url, new { @class = "form-control" })
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.stock, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.stock, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Change" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}