StockBarang/Controllers/StoreController.cs
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using StockBarang.Helper;
using StockBarang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockBarang.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult List(int page = 1)
        {
            var user = Helper.MySqlHelper.GetUserByName(User.Identity.Name);
            var model = new StoreListModel
            {
                Stores = Helper.MySqlHelper.GetStores(user.Id, page)
            };
            Helper.PagingHelper.FillPaging(model, page, Helper.MySqlHelper.GetTotalStores(user.Id), 15);
            return View(model);
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        [HttpPost]
        public ActionResult Create(StoreCreateModel model)
        {
            var user = Helper.MySqlHelper.GetUserByName(User.Identity.Name);
            //try
            //{
            switch (model.Marketplace)
                {
                    case "Tokopedia":
                        MySqlHelper.InsertStore(model, user.Id,
                            TokopediaHelper.FetchStoreName(model.StoreUrl, model.Username, model.Password));
                        break;
                    case "Bukalapak":
                        MySqlHelper.InsertStore(model, user.Id,
                            BukalapakHelper.FetchStoreName(model.StoreUrl, model.Username, model.Password));
                        break;
                }
                return RedirectToAction("List");
            //}
            //catch (Exception ex)
            //{
            //    return View();
            //}
        }

        public ActionResult Delete(string url)
        {
            Helper.MySqlHelper.DeleteStore(url);
            return RedirectToAction("List");
        }
    }
}

StockBarang/Views/Store/Create.cshtml
@model StockBarang.Models.StoreCreateModel
@{
    ViewBag.Title = "Add new Store";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "Store", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Marketplace, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Marketplace, new SelectListItem[]{
                new SelectListItem() { Text= "Tokopedia", Value= "Tokopedia" },
                new SelectListItem() { Text= "Bukalapak", Value= "Bukalapak" } }.AsEnumerable<SelectListItem>())
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StoreUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StoreUrl, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StockBarang/Views/Store/List.cshtml
@model StockBarang.Models.StoreListModel
@{
    ViewBag.Title = "Store List";
}

<h2>@ViewBag.Title.</h2><br />
<button onclick="javascript:location='/store/create'">Add Store</button><br />
<div class="list-group">
    @for (var i = 1; i <= Model.Stores.Count; i++)
    {
        var c = Model.Stores.ElementAt(i-1);
        @:<div class="list-group-item list-group-item-action flex-column align-items-start">
            @:<div class="d-flex w-100 justify-content-between">
                  @:<a href="/store/delete?url=@c.store_url"><small>Delete</small></a>
            @:</div>
            @:<p class="mb-1">
            @:<h4 class="mb-1"><a href="@c.store_url">@c.storename</a></h4>
            @:Marketplace : @c.marketplace<br />
            @:User : @c.username<br />
            @:</p>
        @:</div>
    }
</div>
<nav aria-label="...">
    <ul class="pagination">
        @for (var i = 1; i <= Model.Paging.Count; i++)
        {
            StockBarang.Helper.PagingEntity paging = Model.Paging[i - 1];
            @:<li class="page-item @(paging.disabled?"disabled":"")@(paging.active?"active":"")"><a class="page-link" href="@paging.href" tabindex="-1">@paging.PagingText</a></li>
        }
    </ul>
</nav>